# Generated by Django 2.1.5 on 2019-04-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikesharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='test', max_length=5),
            preserve_default=False,
        ),
    ]
